# Site settings
title: websocks
email: osidenate@gmail.com
description: >
  Nathan Nelson's software projects.
baseurl: ""
url: "http://websocks.net"
github_username:  osidenate

# Build settings
markdown: kramdown
