# Site settings
title: websocks.net - Nathan Nelson
email: nathan@websocks.net
description: >
  Nathan Nelson's software projects.
baseurl: ""
url: "http://websocks.net"
github_username: osidenate

# Build settings
markdown: kramdown
