# Site settings
title: websocks
email: osidenate@gmail.com
description: >
  Nathan Nelson's software projects.
baseurl: "/websocks.net"
url: "http://osidenate.github.io"
github_username:  osidenate

# Build settings
markdown: kramdown
